#SET Environmental Variable
variables:
  ASGNAME: "counter-app"

stages:
  - upload
  - refresh

upload to s3:
  stage: upload
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws s3 sync ./S3/countercode/. s3://code-bucket-repo

instance resfresh:
  stage: refresh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - echo $ASGNAME
    - aws autoscaling start-instance-refresh --auto-scaling-group-name counter-app